icons_format = "{icon}"

[theme]
theme = "solarized-dark"

[icons]
icons = "awesome4"
[icons.overrides]

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "disk_space"
info_type = "available"
alert = 10.0
warning = 15.0

[[block]]
block = "memory"

[[block]]
block = "time"
interval = 1
format = " $timestamp.datetime(f:'%a %d/%m %R:%S') "

[[block]]
block = "battery"
driver = "upower"
device = "DisplayDevice"
missing_format = " missing "
# full_format = " full "
